### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by alexzaworski** [natewiley/cpv2api#1]
Hi,

Are there any plans to get a TLS cert for cpv2api.com? I'd love to be able to use this project for [CodePen Enhancement Suite](https://github.com/alexzaworski/CodePen-Enhancement-Suite) but I don't want everything to break when people are using a secure connection (especially since parts of the extension require https, which would make it even more awkward).

I think letsencrypt is compatible with heroku so there shouldn't be any monetary cost (as far as I understand— server stuff ain't exactly in my wheelhouse).

I'd be happy to help out too, if possible.

**Comment by natewiley** [comment]
Hey @alexzaworski 

There aren't any plans currently to switch it to https, but with Heroku you can use the app url with https https://cpv2api.herokuapp.com 

I should probably add that to the readme or something.. Let me know if it works for you, if not we can try to set something else up.

**Comment by alexzaworski** [comment]
I had no idea that was a thing, sweet! It seems to work fine, time to get to work porting some stuff over 👍 

Thanks!
