### ISSUE TITLE
possible to enable HTTPS?

### ISSUE THREAD

**Issue by dzhurley** [natewiley/cpv2api#10]
Codepen just announced that they are [transitioning to HTTPS](https://blog.codepen.io/2017/03/31/codepen-going-https/). Are there plans for cpv2api.com to track with it and move to HTTPS as well?

**Comment by natewiley** [comment]
Hey, yeah probably will be a good idea to go https.. For now you can use the heroku url https://cpv2api.herokuapp.com

**Comment by dzhurley** [comment]
Sounds good to me, thanks!
