### ISSUE TITLE
/pens endpoints application error

### ISSUE THREAD

**Issue by trevoreyre** [natewiley/cpv2api#11]
It seems that all of the `/pens` endpoints are currently throwing an application error.

![error](https://user-images.githubusercontent.com/6662070/27588861-d01119a6-5b06-11e7-9c86-abb1a3ac606d.PNG)

**Comment by cjoshmartin** [comment]
I am getting the same problem

**Comment by natewiley** [comment]
Pen endpoints should be working again, thanks for letting me know.
