### ISSUE TITLE
Get pens by tag issue

### ISSUE THREAD

**Issue by litekodeGH** [natewiley/cpv2api#6]
Hi:

First of all, thanks for this api.

I've been using this "Get pens by tag" to load pens dynamically and it was working flawlessly. However, now it is acting up in the following way. By including the word "tag" on the following address, it always return the same result from a particular user. 

1) http://cpv2api.com/pens/public/natewiley?tag=tween. is supposed to return pens tagged with the word "tween", however it shows two pens from a different user.

2) The example on the website http://cpv2api.com/pens/public/keithwyland?tag=tenlines, does the same.

3) Even if you write http://cpv2api.com/pens/tag, will return a json from that user.

Thanks

**Comment by natewiley** [comment]
@litekodeGH thanks for reporting this. Should be fixed now, thanks to @alexzaworski
