### ISSUE TITLE
XMLHttpRequest cannot load http://cpv2api.com/pens/public/[*exampleuser*]

### ISSUE THREAD

**Issue by manuelxaguilar** [natewiley/cpv2api#8]
Hey, first of all let me say I really love this project, thanks so much for working on it and sharing it!

This may not be an issue with the API as much as with the browsers themselves, but I still decided to see if anyone has had this issue.

While working on localhost, I attempt to make a single http request with Angular 2's http service. I get the following message only on Chrome and Canary:

> XMLHttpRequest cannot load http://cpv2api.com/pens/public/[*exampleuser*]. Request header field X-XSRF-TOKEN is not allowed by Access-Control-Allow-Headers in preflight response.

This is not happening on Firefox or Safari and I have not tried on a real domain yet. For the time being it's only really annoying to have to debug on these browsers, haha.

Any idea as to what this is? Thanks in advance!

**Comment by natewiley** [comment]
Hey, glad you like the API :) 
Angular adds that header to requests to help with cross site request forgery. (though you have to do something on server with it.)

The API didn't allow it though, so I just added the X-XSRF-TOKEN to allowed headers.
Can you try it again and lmk if it works? 

Thanks

**Comment by manuelxaguilar** [comment]
I was literally working on this project like five minutes ago and it started working so I figured you had already fixed it! I was just waiting for your reply confirming that. So yes, it seems to be functioning perfectly fine now! 

Super quick reply and fix too! 

Thanks!

**Comment by natewiley** [comment]
Haha, awesome good to hear! Thanks :)
